apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    service: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    service: redis
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    service: app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: app
